yii2/school/modules/gsss/controllers/ShopController.php
<?php

namespace school\modules\gsss\controllers;

use app\common\components\Piramida;
use app\models\Form\Event;
use app\models\Piramida\Billing;
use app\models\Piramida\Transaction;
use app\models\Piramida\WalletSource\BitCoin;
use app\models\Piramida\WalletSource\Yandex;
use app\models\Shop\Request;
use app\models\Article;
use app\models\Blog;
use app\models\Form\Shop\Order;
use app\models\Piramida\InRequest;
use app\models\Piramida\Wallet;
use app\models\Praktice;
use app\models\Service;
use app\models\Shop;
use app\models\Shop\Payments;
use app\models\Shop\Product;
use app\models\Shop\TreeNodeGeneral;
use app\models\Union;
use app\models\UnionCategory;
use app\models\User;
use app\modules\Shop\services\Basket;
use common\models\PaySystem;
use common\models\shop\DostavkaItem;
use common\models\shop\PaymentConfig;
use cs\Application;
use cs\services\Str;
use cs\services\VarDumper;
use cs\web\Exception;
use cs\Widget\FileUploadMany\FileUploadMany;
use Yii;
use yii\base\UserException;
use yii\filters\AccessControl;
use yii\grid\DataColumn;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\rbac\Role;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\NewsItem;
use app\models\Chenneling;
use cs\base\BaseController;
use yii\web\HttpException;


class ShopController extends BaseController
{
    public $layout = 'menu';

    public function actionIndex()
    {
        // сохраняю $parent_id
        {
            $parent_id = Yii::$app->request->get('parent_id', null);
            if ($parent_id) {
                Yii::$app->session->set('parent_id', $parent_id);
            }
        }
        return $this->render([
            'tree' => TreeNodeGeneral::getTree(1)
        ]);
    }

    public function actionPartnerProgram()
    {
        return $this->render('partner-program');
    }
    
    public function actionCategory($id)
    {
        // сохраняю $parent_id
        {
            $parent_id = Yii::$app->request->get('parent_id', null);
            if ($parent_id) {
                Yii::$app->session->set('parent_id', $parent_id);
            }
        }
        $treeNode = TreeNodeGeneral::findOne($id);
        if (is_null($treeNode)) {
            throw new Exception('Не найдена категория');
        }
        $items = Product::query()
            ->select([
                'gs_unions_shop_product.*',
            ])
            ->andWhere(['gs_unions_shop_product.is_deleted' => 0])
            ->andWhere(['gs_unions_shop_product.moderation_status' => 1])
            ->andWhere(['gs_shop_tree_products_link.tree_node_id' => $treeNode->id])
            ->innerJoin('gs_shop_tree_products_link', 'gs_shop_tree_products_link.product_id = gs_unions_shop_product.id')
            ->all();

        return $this->render([
            'treeNode' => $treeNode,
            'items'    => $items,
        ]);
    }

    /**
     * Показывает продукт
     *
     * @param int $id идентификатор продукта
     *
     * @return string
     *
     * @throws Exception
     */
    public function actionProduct($id)
    {
        // сохраняю $parent_id
        {
            $parent_id = Yii::$app->request->get('parent_id', null);
            if ($parent_id) {
                Yii::$app->session->set('parent_id', $parent_id);
            }
        }
        $product = Product::find($id);
        if (is_null($product)) {
            throw new Exception('Не найден продукт');
        }
        if ($product->get('moderation_status', 0) == 0) {
            throw new Exception('Продукт не прошел модерацию');
        }

        return $this->render([
            'product' => $product,
        ]);
    }

    /**
     * Выводит результаты посика товаров
     *
     * REQUEST:
     * - text - string - строка поиска
     *
     * @return string
     *
     * @throws Exception
     */
    public function actionSearch()
    {
        $text = self::getParam('text');

        $items = Product::query()
            ->select([
                'gs_unions_shop_product.*',
            ])
            ->where(['like', 'gs_unions_shop_product.name', $text])
            ->all();

        return $this->render([
            'text'  => $text,
        ]);
    }

    /**
     * AJAX
     * Добавление товара в корзину
     * REQUEST
     * - id - int - идентификатор товара gs_unions_shop_product.id
     *
     * @return string
     */
    public function actionBasket_add()
    {
        $id = self::getParam('id');
        $product = Product::find($id);
        if (is_null($product)) {
            return self::jsonErrorId(101, 'Не найден товар');
        }
        $count = Basket::add($product);
        Yii::$app->session->set('shop.help_window_already_showed', 1);

        return self::jsonSuccess($count);
    }

    /**
     * AJAX
     * Добавление товара в корзину
     *
     * REQUEST:
     * - product - int - идентификатор товара gs_unions_shop_product.id
     * - count - int - кол-во товаров
     *
     * @return string
     */
    public function actionBasket_update()
    {
        Basket::setCount(self::getParam('product'), self::getParam('count'));

        return self::jsonSuccess();
    }

    public function actionSet_no_help_window()
    {
        if (Yii::$app->user->isGuest) {
            return self::jsonErrorId(101, 'Пользователь не авторизован');
        }
        Yii::$app->user->identity->update(['is_show_shop_help_window' => 1]);

        return self::jsonSuccess();
    }

    public function actionBasket()
    {
        return $this->render([
            'items' => Basket::get()
        ]);
    }

    /**
     * Удаляет товар из корзины
     *
     * AJAX
     *
     * REQUEST:
     * - id - integer - идентификатор товара
     *
     * @return string
     */
    public function actionBasket_delete()
    {
        $id = self::getParam('id');
        Basket::delete($id);

        return self::jsonSuccess();
    }

    public function actionOrder()
    {
        if (\yii\helpers\ArrayHelper::getValue(Yii::$app->params, 'isTransfere', false) == true) {
            throw new Exception(Yii::$app->params['isTransfere_string']);
        }
        if (count(Basket::get()) == 0) {
            if (is_null(Yii::$app->request->get('product_id'))) {
                return $this->redirect('/');
            }
        }
        $model = new Order();
        if ($model->load(Yii::$app->request->post()) && $model->add()) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render([
                'model' => $model,
            ]);
        }
    }

    /**
     * Выдает форму для оплаты заказа
     *
     * @param int $id bog_shop_requests.id
     *
     * @return string|Response
     * @throws \cs\web\Exception
     */
    public function actionOrder_buy($id)
    {
        if (\yii\helpers\ArrayHelper::getValue(Yii::$app->params, 'isTransfere', false) == true) {
            throw new Exception(Yii::$app->params['isTransfere_string']);
        }
        $request = \app\models\Shop\Request::find($id);
        if (is_null($request)) {
            throw new Exception('Нет такого заказа');
        }
        if ($request->getField('is_paid', 0) == 1) return $this->redirect(['site_cabinet/request', 'id' => $request->getId()]);

        return $this->render([
            'request' => $request,
        ]);
    }

    /**
     * Выдает форму для оплаты заказа
     *
     * @param int $id bog_shop_requests.id
     *
     * @return string|Response
     * @throws \cs\web\Exception
     */
    public function actionOrderBuyOkPay($id)
    {
        if (\yii\helpers\ArrayHelper::getValue(Yii::$app->params, 'isTransfere', false) == true) {
            throw new Exception(Yii::$app->params['isTransfere_string']);
        }
        $request = \app\models\Shop\Request::find($id);
        if (is_null($request)) {
            throw new Exception('Нет такого заказа');
        }
        if ($request->getField('is_paid', 0) == 1) return $this->redirect(['site_cabinet/request', 'id' => $request->getId()]);

        return $this->render('order-buy-ok-pay', [
            'request' => $request,
        ]);
    }

    /**
     * AJAX
     *
     * RESPONSE:
     * - login - string
     * - name - string
     *
     * @return array|string|Response
     */
    public function actionRegistration_ajax()
    {
        $login = strtolower(self::getParam('login'));
        $name = self::getParam('name');
        if (!filter_var($login, FILTER_VALIDATE_EMAIL)) {
            return self::jsonErrorId(106, 'Не верный формат email');
        }
        if (User::query(['email' => $login])->exists()) {
            return self::jsonErrorId(101, 'Пользователь уже существует');
        }
        $user = User::registration_password($login, substr(str_shuffle("01234567890123456789"), 0, 4), [
            'name_first' => $name,
        ]);
        if (Yii::$app->session->get('parent_id')) {
            $user->update(['parent_id' => Yii::$app->session->get('parent_id')]);
        }
        Yii::$app->user->login($user);
        Yii::info(\yii\helpers\VarDumper::dumpAsString(Yii::$app->session->get('parent_id')),'gs\\order\\actionRegistration_ajax');

        return self::jsonSuccess([
            'wallet' => [
                'a' => 0,
                'b' => 0,
            ]
        ]);
    }

    /**
     * AJAX
     *
     * RESPONSE:
     * - login - string
     * - password - string
     *
     * @return array|string|Response
     */
    public function actionLogin_ajax()
    {
        $login = strtolower(self::getParam('login'));
        $password = self::getParam('password');
        if (!filter_var($login, FILTER_VALIDATE_EMAIL)) {
            return self::jsonErrorId(106, 'Не верный формат email');
        }
        $user = User::find(['email' => $login]);

yii2/school/modules/gsss/views/cabinet_wallet/_referal-document.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;

/* @var $this yii\web\View */
/* @var $user \app\models\User */
$this->title = 'Снять деньги';
?>
<p>
    <img src="/images/cabinet_wallet/referal-document/top.jpg" width="100%">
</p>
<h1><?= $user->getName2() ?></h1>
<hr>
<style>
    .cell1 {
        padding: 10px;
        vertical-align: top;
    }

    .cell2 {
        padding: 10px;
        vertical-align: top;
    }
</style>
<table>
    <tr>
        <td class="cell1">
            <img src="<?= $user->getAvatar() ?>" width="180" style="border-radius: 20px;">
        </td>
        <td class="cell2" style="font-size: 200%">
            Здравствуйте! Я ваш проводник в Новый Мир на Новую Землю!
        </td>
    </tr>
    <tr>
        <td class="cell1" style="text-align: right;">
            Тел:
        </td>
        <td class="cell2">
            <?= $user->get('phone_invite', '') ?>
        </td>
    </tr>
    <tr>
        <td class="cell1" style="text-align: right;">
            Почта:
        </td>
        <td class="cell2">
            <?= $user->getEmail() ?>
        </td>
    </tr>
    <tr>
        <td class="cell1">
            <img src="<?= 'data:image/png;base64,' . base64_encode(
                (new \Endroid\QrCode\QrCode())
                    ->setText('https://www.galaxysss.com' . Url::to(['shop/index', 'parent_id' => $user->getId()]))
                    ->setSize(180)
                    ->setPadding(0)
                    ->setErrorCorrection('high')
                    ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0, 'a' => 0])
                    ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255, 'a' => 0])
                    ->setLabelFontSize(16)
                    ->setImageType(\Endroid\QrCode\QrCode::IMAGE_TYPE_PNG)
                    ->get('png')
            )
            ?>" class="thumbnail">
        </td>
        <td class="cell2">
            <p>Реферальная ссылка:</p>

            <p class="alert alert-info"
               style="font-family: 'Courier New', Monospace;"><?= 'https://www.galaxysss.com' . Url::to(['shop/index', 'parent_id' => $user->getId()]); ?></p>
        </td>
    </tr>
</table>
<hr>
С Любовью и Светом на Новой Земле!

yii2/school/modules/gsss/views/cabinet_wallet/_tree.php
<?php
/**
 * Created by PhpStorm.
 * User: Бог-Творец
 * Date: 16.04.2016
 * Time: 20:21
 */
/** $rows = [
 *      [
 *          'id' =>
 *          'value' =>
 *          'parent_id' =>
 *      ],
 * ] */

use app\models\Piramida\Transaction;
use app\models\User;
use app\models\Piramida\Wallet;
use app\models\Piramida\ReferalBonus;

?>


<?php foreach ($rows as $row) { ?>
    <?php $user = $row; ?>
    <?php $nodes = null; ?>
    <?php if (isset($row['nodes'])) $nodes = $row['nodes'];  ?>
    <?php unset($row['nodes']);  ?>
    <?php $userObject = new \common\models\User($row); ?>
    <div class="media">
        <div class="media-left">
            <a href="/user/<?= $user['id'] ?>">
                <img
                    class="media-object"
                    src="<?= $userObject->getAvatar() ?>"
                    style="width: 64px; height: 64px; border-radius: 10px; border: 1px solid #ccc"
                    data-toggle="tooltip"
                    title="<?= $userObject->email ?>"
                    >
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><?= $userObject->getName2() ?></h4>

            <!-- я заработал на нем (от него мне были бонусы)   -->
            <?php
            $iAmId = Yii::$app->user->id;
            $sum = ReferalBonus::find()
            ->where([
                'from' => $user['id'],
                'to'   => $iAmId,
            ])
            ->select([
                'sum(sum)'
            ])
            ->scalar();
            $sum = $sum ? $sum : 0;
            ?>
            <span class="label label-success" title="я заработал на нем (от него мне были бонусы)" data-toggle="tooltip">+ <?= $sum ?> р.</span> |

            <!-- сколько он заработал по партнерской программе   -->
            <?php
            // сколько ему перечислено денег на B по бонусам
            $walletB = Wallet::find()->where([
                'user_id' => $user['id'],
                'type'    => 'B',
            ])->select('id')->scalar();
            if ($walletB) {
                $sum = Transaction::find()
                    ->select([
                        'sum(summa)'
                    ])
                    ->andWhere([
                        'operation' => Transaction::OPERATION_BONUS,
                        'to'        => $walletB,
                    ])
                    ->scalar()
                ;
                $sum = $sum ? $sum : 0;
            } else {
                $sum = 0;
            }
            ?>
            <span class="label label-info" title="сколько он заработал по партнерской программе" data-toggle="tooltip">+ <?= $sum ?> р.</span>

            <?php if (!is_null($nodes)) { ?>
                <?= $this->render('_tree', ['rows' => $nodes]); ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>

yii2/school/modules/gsss/views/cabinet_wallet/childs.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model cs\base\BaseForm */

$this->title = 'Мои дети';

/** @var \app\models\User $user */
$user = Yii::$app->user->identity;
$tree = $user->getTree();
?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
        <?= \cs\Widget\BreadCrumbs\BreadCrumbs::widget([
            'items' => [
                $this->title
            ],
            'home'  => [
                'name' => 'я',
                'url'  => \yii\helpers\Url::to(['site/user', 'id' => Yii::$app->user->id])
            ]
        ]) ?>
        <hr>
        <div class="col-lg-8">

            <ul class="media-list">
                <li class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object"
                                 src="<?= Yii::$app->user->identity->getAvatar() ?>"
                                 style="width: 64px; height: 64px; border-radius: 10px; border: 1px solid #ccc"
                                >
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><?= Yii::$app->user->identity->getName2() ?></h4>
                        <span
                            class="label label-success"><?= Yii::$app->formatter->asCurrency(Yii::$app->user->identity->getWallet('A')->value) ?></span>
                        | <span
                            class="label label-info"><?= Yii::$app->formatter->asCurrency(Yii::$app->user->identity->getWallet('B')->value) ?></span>

                        <?= $this->render('_tree', ['rows' => $tree]) ?>
                    </div>
                </li>
            </ul>

        </div>
        <div class="col-lg-4">
            <?= $this->render('../cabinet/profile_menu/profile_menu') ?>
        </div>
    </div>
</div>

yii2/school/modules/gsss/views/cabinet_wallet/in.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model cs\base\BaseForm */

$this->title = 'Положить деньги';
?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
        <?= \cs\Widget\BreadCrumbs\BreadCrumbs::widget([
            'items' => [
                $this->title
            ],
            'home'  => [
                'name' => 'я',
                'url'  => \yii\helpers\Url::to(['site/user', 'id' => Yii::$app->user->id])
            ]
        ]) ?>
        <hr>

        <div class="col-lg-8">
            <div id="step1">
                <?php
                /** @var \app\models\User $user */
                $user = Yii::$app->user->identity;
                /** @var \app\models\Piramida\Wallet $wallet */
                $wallet = $user->getWallet('A');
                ?>
                <p>Сколько:</p>
                <div class="form-group">
                    <input class="form-control" value="" id="inputValue"/>
                    <p class="hide errorComment error"></p>
                    <p class="helpParagraph"></p>
                </div>
                <?php
                $this->registerJs(<<<JS
                /**
                *
                * @param val
                * @param separator string
                * @param lessOne int кол-во символов после точки, если 0 то точка не выводится, добавляются задние нули работает пока только для 0..2
                * @returns {string}
                */
                function formatAsDecimal (val, separator, lessOne)
                {
                    if (typeof separator == 'undefined') separator = ',';
                    if (typeof lessOne == 'undefined') lessOne = 2;

                    var pStr = '';
                    var original = val;
                    val = parseInt(val);
                    if (val >= 1000000) {
                        var t1 = parseInt(val/1000000);
                        var ost1 = (val - t1 * 1000000);
                        if (ost1 >= 1000) {
                            var t2 = parseInt(ost1/1000);
                            var ost2 = (ost1 - t2 * 1000);
                            var ostStr2 = ost2;
                            if  (t2 == 0) {
                                t2 = '000';
                            } else {
                                if (t2 < 10) {
                                    t2 = '00' + t2;
                                } else if (t2 < 100) {
                                    t2 = '0' + t2;
                                }
                            }
                        } else {
                            t2 = '000';
                            ost2 = ost1;
                        }
                        if  (ost2 == 0) {
                            ostStr2 = '000';
                        } else {
                            if (ost2 < 10) {
                                ostStr2 = '00' + ost2;
                            } else if (ost2 < 100) {
                                ostStr2 = '0' + ost2;
                            }
                        }
                        pStr = t1 + separator + t2 + separator + ostStr2;
                    } else {
                        if (val >= 1000) {
                            var t = parseInt(val/1000);
                            var ost = (val - t * 1000);
                            var ostStr = ost;
                            if  (ost == 0) {
                                ostStr = '000';
                            } else {
                                if (ost < 10) {
                                    ostStr = '00' + ost;
                                } else if (ost < 100) {
                                    ostStr = '0' + ost;
                                }
                            }
                            pStr = t + separator + ostStr;
                        } else {
                            pStr = val;
                        }
                    }

                    var oStr = '';
                    if (lessOne > 0) {
                        oStr = '.';
                        var d = original - parseInt(original);
                        d = d * Math.pow(10, lessOne);
                        d = parseInt(d);
                        if (d == 0) {
                            for (var i = 0; i < lessOne; i++) {
                                oStr = oStr + '0';
                            }
                        } else {
                            if (lessOne == 1) {
                                oStr = d;
                            } else {
                                if (d < 10) {
                                    oStr = oStr + '0' + d;
                                } else {
                                    oStr = oStr + d;
                                }
                            }
                        }
                    }

                    return pStr + oStr;
                }

                /**
                * Вычисляет сумму для поплаты счета пополнения кошелька
                *
                * @param value
                * @returns {number}
                */
                function getPaySum(value)
                {
                    return Math.round(value / (1 - (2 / 100)));
                }

                $('#inputValue').on('input', function() {
                    var i = $(this);
                    if (i.val() != '') {
                        $('.helpParagraph').html('Сумма для оплаты: ' +
                            formatAsDecimal(
                                getPaySum(
                                    $(this).val()
                                )
                            )
                        );
                    } else {
                        $('.helpParagraph').html('Сумма для оплаты: ' + 0);
                    }
                });
                $('.buttonAdd').click(function() {
                    if ($('#inputValue').val() == '') {
                        $('#inputValue').parent().addClass('has-error');
                        $('.errorComment').removeClass('hide').html('Это поле обязательно надо заполнить!').show();
                        return;
                    }
                    ajaxJson({
                        url: '/cabinet/profile/wallet/inAjax',
                        data: {
                            value: $('#inputValue').val()
                        },
                        success: function(ret) {
                            $('#formPayLabel').val('inRequest.' + ret);
                            $('#formPay input[name="short-dest"]').val('Счет #' + ret);
                            $('#formPay input[name="targets"]').val('Счет #' + ret);
                            $('#productPriceForm').val(
                            getPaySum(
                                    $('#inputValue').val()
                                )
                            );
                            $('#formPay').submit();
                        }
                    });
                });
                $('#inputValue').on('focus', function() {
                    $('#inputValue').parent().removeClass('has-error');
                    $('.errorComment').hide();
                });
JS
                );
                ?>
                <div class="col-lg-12 row" style="margin-top: 10px; margin-bottom: 20px;">
                    <div class="btn-group" role="group" aria-label="...">
                        <?php
                        $this->registerJs(<<<JS
    $('.paymentType').click(function () {
        $('#formPay input[name="paymentType"]').attr('value', $(this).data('value'));
        if (!$(this).hasClass('active')) {
            $('.paymentType').removeClass('active');
            $(this).addClass('active');
        }
    });
JS
                        );
                        ?>

                        <button type="button" class="btn btn-default paymentType" data-value="PC">
                            <i class="glyphicon glyphicon-yen" style="margin-right: 4px;"></i> Яндекс.Деньгами
                        </button>
                        <button type="button" class="btn btn-default paymentType active" data-value="AC">
                            <i class="glyphicon glyphicon-credit-card" style="margin-right: 4px;"></i> Банковской картой
                        </button>
                        <button type="button" class="btn btn-default paymentType gsssTooltip" data-value="DI" title="Реквизиты будут высланы ответом после оформления заказа">
                            <i class="glyphicon glyphicon-question-sign" style="margin-right: 4px;"></i> Другие способы
                        </button>
                    </div>
                </div>

                <button class="btn btn-success buttonAdd">Пополнить</button>
            </div>
            <div id="step2" style="display: none;">
                <h2 class="text-center">Идет перенаправление на оплату...</h2>

                <form method="POST" action="https://money.yandex.ru/quickpay/confirm.xml" name="form2" id="formPay">
                    <input type="hidden" name="receiver" value="410011473018906">
                    <input type="hidden" name="formcomment" value="<?= Yii::$app->user->identity->getName2() ?>">
                    <input type="hidden" name="short-dest" value="Счет #<?= $wallet->id ?>">
                    <input type="hidden" name="label" value="inRequest." id="formPayLabel">
                    <input type="hidden" name="quickpay-form" value="donate">
                    <input type="hidden" name="targets" value="Пополнение кошелька #<?= $wallet->id ?>">
                    <input type="hidden" name="sum" value="" data-type="number"
                           id="productPriceForm">
                    <input type="hidden" name="comment" value="">
                    <input type="hidden" name="need-fio" value="false">
                    <input type="hidden" name="need-email" value="false">
                    <input type="hidden" name="need-phone" value="false">
                    <input type="hidden" name="need-address" value="false">
                    <input type="hidden" name="paymentType" value="AC" id="paymentType">

                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 30px;">
                            <div class="btn-group" role="group" aria-label="...">
                                <input type="button" value="Перейти к оплате"
                                       class="btn btn-success btn-lg buttonSubmit" style="width: 400px; border: 2px solid white; border-radius: 20px;">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4">
            <?= $this->render('../cabinet/profile_menu/profile_menu') ?>
        </div>
    </div>

</div>

yii2/school/modules/gsss/views/cabinet_wallet/move.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model cs\base\BaseForm */

$this->title = 'Перевести деньги';
?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
        <?= \cs\Widget\BreadCrumbs\BreadCrumbs::widget([
            'items' => [
                $this->title
            ],
            'home'  => [
                'name' => 'я',
                'url'  => \yii\helpers\Url::to(['site/user', 'id' => Yii::$app->user->id])
            ]
        ]) ?>
        <hr>

        <div class="col-lg-8">
            <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')) {?>
                <div class="alert alert-success">
                    Перевод выполнен успешно.
                </div>

            <?php } else {?>
                <?php $form = ActiveForm::begin([
                    'enableAjaxValidation' => true,
                ]) ?>
                <?= $form->field($model, 'a')->label('Сумма списания с кошелька A') ?>
                <?= $form->field($model, 'b')->label('Сумма списания с кошелька B') ?>
                <?= $form->field($model, 'emailDestination')->label('Получатель')->hint('Введите полный email получателя') ?>
                <?= Html::submitButton('Перевести', [
                    'class' => 'btn btn-success',
                    'style' => 'width:100%;',
                ]) ?>
                <?php ActiveForm::end() ?>
            <?php }?>
        </div>
        <div class="col-lg-4">
            <?= $this->render('../cabinet/profile_menu/profile_menu') ?>
        </div>
    </div>

</div>