yii2/avatar-bank/controllers/CabinetCertificateController.php
<?php

namespace avatar\controllers;

use avatar\models\forms\UserAvatar;
use avatar\models\validate\CardNumberAccept;
use avatar\modules\ETH\ServiceEtherScan;
use avatar\modules\ETH\ServiceEthPlorer;
use common\components\Card;
use common\components\providers\BTC;
use common\components\providers\ETH;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\Config;
use common\models\school\School;
use common\models\school\Sertificate;
use common\models\UserSeed;
use common\payment\BitCoinBlockTrailPayment;
use common\services\Security;
use console\controllers\MoneyRateController;
use cs\services\VarDumper;
use cs\web\Exception;
use cs\Widget\FileUpload4\ModelFields;
use Yii;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\StringHelper;
use yii\httpclient\Client;
use yii\imagine\Image;
use yii\web\Response;

class CabinetCertificateController extends \avatar\controllers\CabinetBaseController
{
    public $type_id = 11;

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render();
    }

    public function actionAdd()
    {
        $model = new \avatar\models\forms\school\Certificate(['_school_id' => 2, '_type_id' => $this->type_id]);

        if ($model->load(Yii::$app->request->post()) && $model->insert()) {
            Yii::$app->session->setFlash('form', 1);
            $i = \common\models\school\Sertificate::findOne($model->id);
            $i->user_id = Yii::$app->user->id;
            $i->save();
        }

        return $this->render([
            'model' => $model,
        ]);
    }


    public function actionEdit($id)
    {
        $model = \avatar\models\forms\school\Certificate::findOne($id);
        $model->_school_id = 2;
        $model->_type_id = $this->type_id;

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        $Certificate = \avatar\models\forms\school\Certificate::findOne($id);

        return $this->render([
            'item' => $Certificate,
        ]);
    }


    public function actionDelete($id)
    {
        \avatar\models\forms\school\Certificate::findOne($id)->delete();

        return self::jsonSuccess();
    }
}

yii2/avatar-bank/views/cabinet-certificate/add.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \avatar\models\forms\school\Certificate */

$this->title = 'Добавить сертификат';

?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="col-lg-8">
        <?php if (!is_null($id = Yii::$app->session->getFlash('form'))) : ?>

            <div class="alert alert-success">
                Успешно добавлено.
            </div>

        <?php else: ?>


            <div class="row">
                <div class="col-lg-8">
                    <?php $form = ActiveForm::begin([
                        'options' => ['enctype' => 'multipart/form-data'],
                    ]); ?>
                    <?= $model->field($form, 'name') ?>
                    <?= $model->field($form, 'description') ?>
                    <?= $model->field($form, 'image') ?>


                    <hr>
                    <div class="form-group">
                        <?= Html::submitButton('Добавить', [
                            'class' => 'btn btn-default',
                            'name'  => 'contact-button',
                            'style' => 'width:100%',
                        ]) ?>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>

        <?php endif; ?>
    </div>
    <div class="col-lg-4">
        <?= $this->render('../cabinet/_menu') ?>
    </div>
</div>

yii2/avatar-bank/views/cabinet-certificate/edit.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \avatar\models\forms\school\Certificate */

$this->title = $model->name;

?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>

        <div class="col-lg-8">
            <?php if (Yii::$app->session->hasFlash('form')) { ?>
                <div class="alert alert-success">
                    Успешно обновлено.
                </div>

            <?php } else { ?>

                <div class="row">
                    <div class="col-lg-8">
                        <?php $form = ActiveForm::begin([
                            'id'      => 'contact-form',
                            'options' => ['enctype' => 'multipart/form-data'],
                        ]); ?>
                        <?= $model->field($form, 'name') ?>
                        <?= $model->field($form, 'description') ?>
                        <?= $model->field($form, 'image') ?>

                        <hr>
                        <div class="form-group">
                            <?= Html::submitButton('Обновить', [
                                'class' => 'btn btn-default',
                                'name'  => 'contact-button',
                                'style' => 'width:100%',
                            ]) ?>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>

            <?php } ?>
        </div>
        <div class="col-lg-4">
            <?= $this->render('../cabinet/_menu') ?>
        </div>
</div>

yii2/avatar-bank/views/cabinet-certificate/index.php
<?php

/** $this \yii\web\View  */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = 'Все школы';


?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>

        <div class="col-lg-8">
            <p><a href="<?= Url::to(['cabinet-certificate/add']) ?>" class="btn btn-default">Добавить</a></p>

        <?php \yii\widgets\Pjax::begin(); ?>
        <?php
        $this->registerJS(<<<JS
$('[data-toggle="tooltip"]').tooltip();
$('.buttonDelete').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
    if (confirm('Подтвердите удаление')) {
        var button = $(this);
        var id = $(this).data('id');
        ajaxJson({
            url: '/cabinet-certificate/delete' + '?' + 'id' + '=' + id,
            success: function (ret) {
                $('#modalInfo').on('hidden.bs.modal', function() {
                    button.parent().parent().remove();
                }).modal();
            }
        });
    }
});

$('.rowTable').click(function() {
    window.location = '/cabinet-certificate/edit' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonSchool').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-certificate/view' + '?' + 'id' + '=' + $(this).data('id');
});
JS
        );
        ?>
        <?= \yii\grid\GridView::widget([
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query'      => \common\models\school\Sertificate::find()
                    ->where(['user_id' => Yii::$app->user->id])
                ,
                'pagination' => [
                    'pageSize' => 20,
                ],
            ]),
            'tableOptions' => [
                'class' => 'table table-striped table-hover',
            ],
            'rowOptions'   => function ($item) {
                $data = [
                    'data'  => ['id' => $item['id']],
                    'role'  => 'button',
                    'class' => 'rowTable'
                ];
                return $data;
            },
            'columns'      => [
                'id',
                'name',
                'school_id',
                [
                    'header'  => 'Картинка',
                    'content' => function ($item) {
                        $i = ArrayHelper::getValue($item, 'image', '');
                        if ($i == '') return '';

                        return Html::img(\common\widgets\FileUpload7\FileUpload::getFile($i, 'crop'), [
                            'class'  => "thumbnail",
                            'width'  => 80,
                            'height' => 80,
                            'style'  => 'margin-bottom: 0px;',
                        ]);
                    }
                ],
                [
                    'header'  => 'Удалить',
                    'content' => function ($item) {
                        return Html::button('Удалить', [
                            'class' => 'btn btn-danger btn-xs buttonDelete',
                            'data'  => [
                                'id' => $item['id'],
                            ]
                        ]);
                    }
                ],
            ],
        ]) ?>
        <?php \yii\widgets\Pjax::end(); ?>
        </div>
        <div class="col-lg-4">
            <?= $this->render('../cabinet/_menu') ?>
        </div>
</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

yii2/avatar-bank/views/cabinet-certificate/view.php
<?php

/** @var $this \yii\web\View  */
/** @var $school \common\models\school\School  */
/* @var $item \avatar\models\forms\school\Certificate */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = $school->name;


?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="col-lg-4">
        <?= $this->render('../cabinet-school/_menu', ['school' => $school]) ?>
    </div>
    <div class="col-lg-8">
        test
    </div>
</div>