yii2/avatar-bank/controllers/CabinetSchoolPagesController.php
<?php

namespace avatar\controllers;

use avatar\models\forms\UserAvatar;
use avatar\models\validate\CardNumberAccept;
use avatar\modules\ETH\ServiceEtherScan;
use avatar\modules\ETH\ServiceEthPlorer;
use common\components\Card;
use common\components\providers\BTC;
use common\components\providers\ETH;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\Config;
use common\models\school\Kurs;
use common\models\school\Lesson;
use common\models\school\Master;
use common\models\school\Page;
use common\models\school\PageBlock;
use common\models\school\PageBlockContent;
use common\models\school\Potok;
use common\models\school\School;
use common\models\UserSeed;
use common\payment\BitCoinBlockTrailPayment;
use common\services\Security;
use console\controllers\MoneyRateController;
use cs\services\VarDumper;
use cs\web\Exception;
use cs\Widget\FileUpload4\ModelFields;
use Yii;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\StringHelper;
use yii\httpclient\Client;
use yii\imagine\Image;
use yii\web\Response;

class CabinetSchoolPagesController extends CabinetSchoolBaseController
{
    /**
     * @return string
     */
    public function actionIndex($id)
    {
        $this->isAccess($id);
        $school = School::findOne($id);

        return $this->render(['school' => $school]);
    }

    public function actionAdd($id)
    {
        $this->isAccess($id);
        $model = new Page();
        $school = School::findOne($id);
        $potok_id = self::getParam('potok_id');
        if ($potok_id) {
            $potok = Potok::findOne($potok_id);
            if (is_null($potok)) throw new Exception('Не найден potok_id');
            // проверяю что параметр potok_id входит в школу
            $this->isAccess($potok->getKurs()->school_id);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            Yii::$app->session->setFlash('form', 1);
            $model->school_id = $id;
            $model->save();
            $model->id = $model::getDb()->lastInsertID;
            $block = new PageBlockContent([
                'content' => file_get_contents(Yii::getAlias('@avatar/views/cabinet-school-pages/init.json')),
                'page_id' => $model->id,
                'type_id' => 1,
            ]);
            $block->save();
            if ($potok_id) {
                $potok = Potok::findOne($potok_id);
                $potok->page_id = $model->id;
                $potok->save();
            }
        }

        return $this->render([
            'model' => $model, 'school' => $school,
        ]);
    }

    /**
     * @param int $id страница
     *
     * @return string
     */
    public function actionConstructor($id)
    {
        $this->layout = 'blank';

        $page = Page::findOne($id);
        $this->isAccess($page->school_id);
        $school = School::findOne($page->school_id);

        return $this->render([
            'page'   => $page,
            'school' => $school,
        ]);
    }


    public function actionEdit($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'school' => $school,
        ]);
    }

    public function actionCopy($id)
    {
        $page = Page::findOne($id);
        $model = new \avatar\models\forms\CabinetSchoolPagesCopy(['id' => $id]);
        $this->isAccess($page->school_id);
        $school = School::findOne($page->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->action();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'page'   => $page,
            'school' => $school,
        ]);
    }

    public function actionMove($id)
    {
        $page = Page::findOne($id);
        $model = new \avatar\models\forms\CabinetSchoolPagesMove(['id' => $id]);
        $this->isAccess($page->school_id);
        $school = School::findOne($page->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->action();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'page'   => $page,
            'school' => $school,
        ]);
    }

    /**
     * @param int $id school_page.id
     *
     * @return string
     */
    public function actionView($id)
    {
        $page = Page::findOne($id);
        $this->isAccess($page->school_id);
        $school = School::findOne($page->school_id);

        return $this->render([
            'page'   => $page,
            'school' => $school,
        ]);
    }

    public function actionSeo($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'school' => $school,
        ]);
    }

    public function actionStat($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        return $this->render([
            'model'  => $model,
            'school' => $school,
        ]);
    }

    public function actionBody($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'school' => $school,
        ]);
    }

    public function actionSocialNet($id)
    {
        $model = \avatar\models\forms\school\Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model' => $model, 'school' => $school,
        ]);
    }

    public function actionHeaderFooter($id)
    {
        $this->isAccess($id);
        $model = School::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'school' => $model,
        ]);
    }

    public function actionIndexHeaderFooter($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model'  => $model,
            'school' => $school,
        ]);
    }

    public function actionFavicon($id)
    {
        $model = \avatar\models\forms\school\Page::findOne($id);
        $this->isAccess($model->school_id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model' => $model, 'school' => $school,
        ]);
    }


    public function actionDelete($id)
    {
        $model = Page::findOne($id);
        $this->isAccess($model->school_id);

        $rows = PageBlockContent::find()->where(['page_id' => $id])->all();
        /** @var \common\models\school\PageBlockContent $item */
        foreach ($rows as $item) {
            $item->delete();
        }
        Page::findOne($id)->delete();

        return self::jsonSuccess();
    }
}

yii2/avatar-bank/views/cabinet-school-pages/add.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\school\Page */
/* @var $school \common\models\school\School */

$this->title = 'Добавить страницу';

?>
<div class="container">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (!is_null($id = Yii::$app->session->getFlash('form'))) : ?>

        <div class="alert alert-success">
            Успешно добавлено.
        </div>

        <p>
            <a href="<?= \yii\helpers\Url::to(['cabinet-school-pages/index', 'id' => $school->id]) ?>" class="btn btn-success">Все страницы</a>
        </p>

    <?php else: ?>


        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'url') ?>
                <?= $form->field($model, 'tilda_page_id') ?>


                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Добавить', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php endif; ?>


</div>

yii2/avatar-bank/views/cabinet-school-pages/block-add.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $items \common\models\school\PageBlock[] */

?>
<?php /** @var \common\models\school\PageBlock $item */ ?>
<?php foreach ($items as $item) { ?>
    <div class="block" id="<?= $item->id ?>">
        <button class="btn btn-default buttonBlockItem" data-id="<?= $item->id ?>"><?= $item->name ?></button>
        <?php if ($item->image) { ?>
            <p><img src="<?= $item->image ?>" style="width: 100%;" class="thumbnail"></p>
        <?php } ?>
    </div>
<?php } ?>

yii2/avatar-bank/views/cabinet-school-pages/copy.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $page \common\models\school\Page */
/* @var $model \avatar\models\forms\CabinetSchoolPagesCopy */
/* @var $school \common\models\school\School */

$this->title = 'Копировать страницу';

?>
<div class="container">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (!is_null($id = Yii::$app->session->getFlash('form'))) : ?>

        <div class="alert alert-success">
            Успешно скопировано.
        </div>

        <p>
            <a href="<?= \yii\helpers\Url::to(['cabinet-school-pages/index', 'id' => $school->id]) ?>" class="btn btn-success">Все страницы</a>
        </p>

    <?php else: ?>


        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'link') ?>


                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Копировать', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php endif; ?>


</div>

yii2/avatar-bank/views/cabinet-school-pages/edit.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\school\Page */
/* @var $school \common\models\school\School */

$this->title = $model->name;

?>
<div class="container">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('form')) { ?>
        <div class="alert alert-success">
            Успешно обновлено.
        </div>

        <p>
            <a href="<?= \yii\helpers\Url::to(['cabinet-school-pages/index', 'id' => $school->id]) ?>" class="btn btn-success">Все страницы</a>
        </p>

    <?php } else { ?>

        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'id'      => 'contact-form',
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'url') ?>
                <?= $form->field($model, 'tilda_page_id') ?>

                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Обновить', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php } ?>


</div>

yii2/avatar-bank/views/cabinet-school-pages/favicon.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \avatar\models\forms\school\Page */
/* @var $school \common\models\school\School */

$this->title = $model->name;

?>
<div class="container">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('form')) { ?>
        <div class="alert alert-success">
            Успешно обновлено.
        </div>

        <p>
            <a href="<?= \yii\helpers\Url::to(['cabinet-school-pages/index', 'id' => $school->id]) ?>" class="btn btn-success">Все страницы</a>
        </p>

    <?php } else { ?>

        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'id'      => 'contact-form',
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $model->field($form, 'favicon') ?>

                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Обновить', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php } ?>


</div>

yii2/avatar-bank/views/cabinet-school-pages/index.php
<?php

/** @var $this \yii\web\View */
/** @var $school \common\models\school\School */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = 'Все страницы';


?>

<div class="container">


    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <p>
        <a href="<?= Url::to(['cabinet-school-pages/add', 'id' => $school->id]) ?>" class="btn btn-default">Добавить</a>
        <a href="<?= Url::to(['cabinet-school-pages/header-footer', 'id' => $school->id]) ?>" class="btn btn-default">Шапка
            и подвал</a>
    </p>

    <?php \yii\widgets\Pjax::begin(); ?>
    <?php
    $this->registerJS(<<<JS
$('[data-toggle="tooltip"]').tooltip();
$('.buttonDelete').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
    if (confirm('Подтвердите удаление')) {
        var button = $(this);
        var id = $(this).data('id');
        ajaxJson({
            url: '/cabinet-school-pages/delete' + '?' + 'id' + '=' + id,
            success: function (ret) {
                $('#modalInfo').on('hidden.bs.modal', function() {
                    button.parent().parent().remove();
                }).modal();
            }
        });
    }
});

$('.buttonEdit').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/edit' + '?' + 'id' + '=' + $(this).data('id');
});

$('.buttonSeo').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/seo' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonStat').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/stat' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonBody').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/body' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonConstructor').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/constructor' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonFavicon').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/favicon' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonSs').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/social-net' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonHeader').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/index-header-footer' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonCopy').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/copy' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonMove').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-pages/move' + '?' + 'id' + '=' + $(this).data('id');
});
$('.buttonPotok').click(function(e) {
    e.preventDefault();
    e.stopPropagation();
    window.location = '/cabinet-school-potok/view' + '?' + 'id' + '=' + $(this).data('id');
});
JS
    );
    $model = new \avatar\models\search\Page();
    $provider = $model->search(Yii::$app->request->get(), ['school_id' => $school->id], ['defaultOrder' => ['id' => SORT_ASC]])
    ?>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => $provider,
        'filterModel'  => $model,
        'tableOptions' => [
            'class' => 'table table-striped table-hover',
        ],
        'rowOptions'   => function ($item) {
            $data = [
                'data'  => ['id' => $item['id']],
                'role'  => 'button',
                'class' => 'rowTable',
            ];
            return $data;
        },
        'columns'      => [
            [
                'attribute' => 'id',
                'headerOptions' => ['style' => 'width:5%'],
            ],
            [
                'attribute' => 'name',
                'headerOptions' => ['style' => 'width:30%'],
            ],
            [
                'header'    => 'Ссылка',
                'headerOptions' => ['style' => 'width:30%'],
                'attribute' => 'url',
                'content'   => function (\common\models\school\Page $item) {
                    return Html::tag('code', \common\helpers\Html::a($item->url, $item->getUrl(), ['target' => '_blank']));
                },
            ],
            [
                'header'        => 'Функции',
                'headerOptions' => ['style' => 'width:15%'],
                'content'       => function ($item) {
                    $functions = [
                        [
                            'class' => 'buttonEdit',
                            'name'  => 'Редактировать',
                        ],
                        [
                            'class' => 'buttonCopy',
                            'name'  => 'Копировать',
                        ],
                        [
                            'class' => 'buttonMove',
                            'name'  => 'Переместить',
                        ],
                        [
                            'class' => 'buttonFavicon',
                            'name'  => 'Favicon',
                            'title' => 'Иконка страницы во вкладке браузера',
                            'isOn'  => function ($item) {
                                if (\cs\Application::isEmpty($item['favicon'])) {
                                    return false;
                                } else {
                                    return true;
                                }
                            },
                        ],
                        [
                            'class' => 'buttonSs',
                            'name'  => 'СоцСети',
                            'title' => 'Мета информация для формирования презентационного бока при репосте страницы в СоцСетях',
                            'isOn'  => function ($item) {
                                if (\cs\Application::isEmpty($item['facebook_image'])) {
                                    return false;
                                } else {
                                    return true;
                                }
                            },
                        ],
                        [
                            'class' => 'buttonBody',
                            'name'  => 'Body',
                            'title' => 'HTML код дополнительный для вставки в страницу',
                            'isOn'  => function ($item) {
                                if (\cs\Application::isEmpty($item['body'])) {
                                    return false;
                                } else {
                                    return true;
                                }
                            },
                        ],
                        [
                            'class' => 'buttonSeo',
                            'name'  => 'SEO',
                            'title' => 'Заголовок страницы, описание и ключевые слова',
                            'isOn'  => function ($item) {
                                if (\cs\Application::isEmpty($item['title'])) {
                                    return false;
                                } else {
                                    return true;
                                }
                            },
                        ],
                        [
                            'class' => 'buttonHeader',
                            'name'  => 'Шапка и подвал',
                            'isOn'  => function ($item) {
                                $header_id = $item['header_id'];
                                $footer_id = $item['footer_id'];
                                if ($header_id) {
                                    return true;
                                }
                                if ($footer_id) {
                                    return true;
                                }

                                return false;
                            },
                        ],
                        [
                            'class' => 'buttonStat',
                            'name'  => 'Статистика',
                        ],
                    ];

                    $b1 = Html::button('Конструктор', ['class' => 'btn btn-default btn-xs buttonConstructor', 'data' => ['id' => $item['id']]]);
                    $contentB2 = join('', [
                        Html::tag('span', null, ['class' => 'caret']),
                        Html::tag('span', 'Toggle Dropdown', ['class' => 'sr-only']),
                    ]);
                    $b2 = Html::button($contentB2, ['class' => 'btn btn-default dropdown-toggle btn-xs', 'data' => ['toggle' => 'dropdown'], 'aria-haspopup' => 'true', 'aria-expanded' => ['false']]);
                    $items = [];
                    foreach ($functions as $item1) {
                        $class = [
                            $item1['class'],
                        ];
                        if (isset($item1['isOn'])) {
                            $function = $item1['isOn'];
                            $result = $function($item);
                            if ($result) {
                                $class[] = 'btn-info';
                            }
                        }
                        $options = [
                            'class' => join(' ', $class),
                            'data'  => [
                                'id' => $item['id'],
                            ],
                        ];
                        if (isset($item1['title'])) $options['title'] = $item1['title'];
                        $items[] = Html::tag('li', Html::a($item1['name'], 'javascript:void(0);', $options));
                    }
                    $ul = Html::tag('ul', join('', $items), ['class' => 'dropdown-menu']);

                    $b = Html::tag('div', $b1 . $b2 . $ul, ['class' => 'btn-group']);

                    return $b;
                },
            ],
            [
                'header'  => 'Поток',
                'headerOptions' => ['style' => 'width:10%'],
                'content' => function ($item) {
                    $potok = \common\models\school\Potok::findOne(['page_id' => $item['id']]);
                    if (!is_null($potok)) {
                        return Html::button('Поток', [
                            'class' => 'btn btn-success btn-xs buttonPotok',
                            'data'  => [
                                'id' => $potok->id,
                            ],
                        ]);
                    }
                    return '';
                },
            ],
            [
                'header'  => 'Удалить',
                'headerOptions' => ['style' => 'width:10%'],
                'content' => function ($item) {
                    return Html::button('Удалить', [
                        'class' => 'btn btn-danger btn-xs buttonDelete',
                        'data'  => [
                            'id' => $item['id'],
                        ],
                    ]);
                },
            ],
        ],
    ]) ?>
    <?php \yii\widgets\Pjax::end(); ?>



</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

yii2/avatar-bank/views/cabinet-school-pages/view.php
<?php

/** @var $this \yii\web\View */
/** @var $school \common\models\school\School */
/** @var $page  \common\models\school\Page */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = $page->name;

?>

<div class="container">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <hr>

    <?= \yii\widgets\DetailView::widget([
        'model'      => $page,
        'attributes' => [
            [
                'label'          => 'Наименование',
                'captionOptions' => [
                    'style' => 'width: 30%',
                ],
                'value'          => $page->name,
            ],
            'url',
        ],
    ]) ?>
    <p><a href="<?= $page->getUrl() ?>" target="_blank"><?= $page->url ?></a></p>

    <p><a href="<?= Url::to(['cabinet-school-pages/edit', 'id' => $page->id]) ?>" class="btn btn-default">Редактировать</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/favicon', 'id' => $page->id]) ?>" class="btn btn-default">favicon</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/social-net', 'id' => $page->id]) ?>" class="btn btn-default">СоцСети</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/body', 'id' => $page->id]) ?>" class="btn btn-default">Body</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/seo', 'id' => $page->id]) ?>" class="btn btn-default">SEO</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/constructor', 'id' => $page->id]) ?>" class="btn btn-default">Конструктор</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/stat', 'id' => $page->id]) ?>" class="btn btn-default">Статистика</a></p>
    <p><a href="<?= Url::to(['cabinet-school-pages/index-header-footer', 'id' => $page->id]) ?>" class="btn btn-default">Шапка и подвал</a></p>

    <?php $potok = \common\models\school\Potok::findOne(['page_id' => $page->id]); ?>
    <?php if (!is_null($potok)) { ?>
        <p><a href="<?= Url::to(['cabinet-school-potok/view', 'id' => $potok->id]) ?>" class="btn btn-default">Поток</a></p>
    <?php } ?>



</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>