yii2/avatar-bank/controllers/AdminTaskListController.php
<?php

namespace avatar\controllers;

use avatar\models\forms\UserAvatar;
use avatar\models\validate\CardNumberAccept;
use avatar\modules\ETH\ServiceEtherScan;
use avatar\modules\ETH\ServiceEthPlorer;
use common\components\Card;
use common\components\providers\BTC;
use common\components\providers\ETH;
use common\models\avatar\Currency;
use common\models\avatar\UserBill;
use common\models\Config;
use common\models\school\Master;
use common\models\school\School;
use common\models\task\Category;
use common\models\task\Task;
use common\models\UserSeed;
use common\payment\BitCoinBlockTrailPayment;
use common\services\Security;
use console\controllers\MoneyRateController;
use cs\services\VarDumper;
use cs\web\Exception;
use cs\Widget\FileUpload4\ModelFields;
use Yii;
use yii\base\Event;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\StringHelper;
use yii\httpclient\Client;
use yii\imagine\Image;
use yii\web\Response;

class AdminTaskListController extends \avatar\controllers\AdminBaseController
{

    /**
     * @return string
     */
    public function actionIndex($id)
    {
        $school = School::findOne($id);
        return $this->render(['school' => $school]);
    }

    /**
     * @return string
     */
    public function actionAjail($id)
    {
        $school = School::findOne($id);

        return $this->render(['school' => $school]);
    }

    /**
     * - item_id - идентификатор задачи
     * - list_id - идентификатор статуса
     *
     * @return string
     */
    public function actionSet()
    {
        $item_id = self::getParam('item_id');
        $list_id = self::getParam('list_id');
        $Task = Task::findOne($item_id);
        $Task->status = $list_id;
        $Task->save();

        return self::jsonSuccess();
    }

    public function actionAdd($id)
    {
        $model = new Task();
        Event::on(Task::className(), 'EVENT_BEFORE_INSERT', function (Task $item) {
            $item->price = $item->price * 100;
        });
        $school = School::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            Yii::$app->session->setFlash('form', 1);
            $model->user_id = Yii::$app->user->id;
            $model->school_id = $id;
            $model->save();
        }

        return $this->render([
            'model' => $model,'school' => $school
        ]);
    }


    public function actionEdit($id)
    {
        $model = Task::findOne($id);
        $school = School::findOne($model->school_id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('form', 1);
        }

        return $this->render([
            'model' => $model,'school' => $school
        ]);
    }


    public function actionDelete($id)
    {
        Task::findOne($id)->delete();

        return self::jsonSuccess();
    }
}

yii2/avatar-bank/views/admin-task-list/add.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\task\Task */
/* @var $school \common\models\school\School */

$this->title = 'Добавить задачу';

?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (!is_null($id = Yii::$app->session->getFlash('form'))) : ?>

        <div class="alert alert-success">
            Успешно добавлено.
        </div>

    <?php else: ?>


        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'price')->hint('Кол-во атомов (копеек)') ?>
                <?= $form->field($model, 'currency_id')->dropDownList(
                    ArrayHelper::merge(
                            ['- Не выбрано -'],
                        ArrayHelper::map(
                            \common\models\piramida\Currency::find()->orderBy(['code' => SORT_ASC])->all(),
                            'id',
                            'code'
                        )
                    )
                ) ?>
                <?= $form->field($model, 'category_id')->dropDownList(
                    ArrayHelper::merge(
                        ['- Не выбрано -'],
                        ArrayHelper::map(
                            \common\models\task\Category::find()->orderBy(['sort_index' => SORT_ASC])->where(['school_id' => $school->id])->all(),
                            'id',
                            'name'
                        )
                    )
                ) ?>
                <?= $form->field($model, 'content')->textarea(['rows' => 10]) ?>


                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Добавить', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php endif; ?>
    </div>

</div>

yii2/avatar-bank/views/admin-task-list/ajail.php
<?php

/** @var $this \yii\web\View */

/** @var $school \common\models\school\School */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = 'Все задачи';
?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

        <p><a href="<?= Url::to(['admin-task-list/add', 'id' => $school->id]) ?>" class="btn btn-default">Добавить</a>
        </p>

        <?php
        $this->registerJS(<<<JS


JS
        );
        ?>
        <style>
            .container123 {
                margin: 0 auto;
            }

            .connectedSortable {
                border: 1px solid #eee;
                width: 220px;
                min-height: 20px;
                list-style-type: none;
                margin: 0;
                padding: 5px;
                float: left;
                margin-right: 10px;
            }

            .connectedSortable li {
                margin: 0 5px 5px 5px;
                padding: 5px;
                width: 200px;
                border: 1px solid #eee;
            }

            /*.ui-state-highlight { height: 1.2em; line-height: 1.2em; }*/
        </style>
        <?php $this->registerJsFile('https://code.jquery.com/ui/1.12.1/jquery-ui.js', ['depends' => ['\yii\web\JqueryAsset']]);
        $this->registerJs(<<<JS


$(".connectedSortable").on("sortreceive", function(event, ui) {
    console.log([event, ui,$(this)]);
    var item_id = $(ui.item[0]).data('id');
    var list_id = $(event.currentTarget).data('id');
    console.log([item_id,list_id]);
    ajaxJson({
        url:"/admin-task-list/set",
        data: {
            item_id:item_id,
            list_id:list_id,
        },
        success: function(ret) {
            
        }
    });
});
JS
        );

        ?>


        <h2 class="page-header">Без категории</h2>

        <table border="0" style="height: 50px;">
            <tr>
                <td style="width: 230px;font-weight: bold;">Не распределено</td>
                <td style="width: 230px;font-weight: bold;">Исполняется</td>
                <td style="width: 230px;font-weight: bold;">Проверяется</td>
                <td style="width: 230px;font-weight: bold;">Выполнено</td>
            </tr>
        </table>

        <div class="row">
            <div class="container123">

                <?php
                $rows1 = \common\models\task\Task::find()->where(['school_id' => $school->id])->andWhere(['or', ['status' => null], ['status' => 0]])->all();
                $rows2 = \common\models\task\Task::find()->where(['school_id' => $school->id, 'status' => 1])->all();
                $rows3 = \common\models\task\Task::find()->where(['school_id' => $school->id, 'status' => 2])->all();
                $rows4 = \common\models\task\Task::find()->where(['school_id' => $school->id, 'status' => 3])->all();
                ?>
                <?php
                $this->registerJs(<<<JS
$( ".sortable1, .sortable2, .sortable3, .sortable4" ).sortable({
    placeholder: "ui-state-highlight",
    connectWith: ".connectedSortable"
});
JS
                );
                ?>
                <ul class="connectedSortable sortable1" data-id="0">
                    <?php /** @var \common\models\task\Task $item */ ?>
                    <?php foreach ($rows1 as $item) { ?>
                        <?= $this->render('i', ['item' => $item]) ?>
                    <?php } ?>
                </ul>

                <ul class="connectedSortable sortable2" data-id="1">
                    <?php /** @var \common\models\task\Task $item */ ?>
                    <?php foreach ($rows2 as $item) { ?>
                        <?= $this->render('i', ['item' => $item]) ?>
                    <?php } ?>
                </ul>

                <ul class="connectedSortable sortable3" data-id="2">
                    <?php /** @var \common\models\task\Task $item */ ?>
                    <?php foreach ($rows3 as $item) { ?>
                        <?= $this->render('i', ['item' => $item]) ?>
                    <?php } ?>
                </ul>

                <ul class="connectedSortable sortable4" data-id="3">
                    <?php /** @var \common\models\task\Task $item */ ?>
                    <?php foreach ($rows4 as $item) { ?>
                        <?= $this->render('i', ['item' => $item]) ?>
                    <?php } ?>
                </ul>

            </div>
        </div>



    </div>
</div>

</div>

yii2/avatar-bank/views/admin-task-list/edit.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use app\models\UnionCategory;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \avatar\models\forms\school\Potok */
/* @var $school \common\models\school\School */

$this->title = $model->name;


?>
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('form')) { ?>
        <div class="alert alert-success">
            Успешно обновлено.
        </div>

    <?php } else { ?>

        <div class="row">
            <div class="col-lg-8">
                <?php $form = ActiveForm::begin([
                    'id'      => 'contact-form',
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'price')->hint('Кол-во атомов (копеек)') ?>
                <?= $form->field($model, 'currency_id')->dropDownList(
                    ArrayHelper::merge(
                        ['- Не выбрано -'],
                        ArrayHelper::map(
                            \common\models\piramida\Currency::find()->orderBy(['code' => SORT_ASC])->all(),
                            'id',
                            'code'
                        )
                    )
                ) ?>
                <?= $form->field($model, 'category_id')->dropDownList(
                    ArrayHelper::map(
                        \common\models\task\Category::find()->orderBy(['sort_index' => SORT_ASC])->where(['school_id' => $school->id])->all(),
                        'id',
                        'name'
                    )
                ) ?>
                <?= $form->field($model, 'content')->textarea(['rows' => 10]) ?>


                <hr>
                <div class="form-group">
                    <?= Html::submitButton('Обновить', [
                        'class' => 'btn btn-default',
                        'name'  => 'contact-button',
                        'style' => 'width:100%',
                    ]) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php } ?>
    </div>

</div>

yii2/avatar-bank/views/admin-task-list/i.php
<?php
/**
 * Created by PhpStorm.
 * User: Ra-m-ha
 * Date: 31.12.2018
 * Time: 0:44
 */

?>
<?php /** @var \common\models\task\Task $item */ ?>

<li class="ui-state-default" data-id="<?= $item->id ?>">
    <span class="label label-info"><a href="/admin-task-list/edit?id=<?= $item->id ?>">#<?= $item->id ?></a></span> <?= $item->name ?>
    <?php if ($item->executer_id) { ?>
    <?php $user = \common\models\UserAvatar::findOne($item->executer_id) ?>
        <br>
        <img src="<?= $user->getAvatar() ?>" width="30" class="img-circle" title="<?= \yii\helpers\Html::encode($user->getName2()) ?>" data-toggle="tooltip"/>
    <?php } ?>
</li>

yii2/avatar-bank/views/admin-task-list/index.php
<?php

/** @var $this \yii\web\View */
/** @var $school \common\models\school\School */

use yii\helpers\Url;
use app\services\GsssHtml;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\services\GetArticle\Collection;

$this->title = 'Все задачи';

?>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>

    <p><a href="<?= Url::to(['admin-task-list/add', 'id' => $school->id]) ?>" class="btn btn-default">Добавить</a>
        <a href="<?= Url::to(['admin-task-list/ajail', 'id' => $school->id]) ?>" class="btn btn-default">Статусы</a></p>

    <?php \yii\widgets\Pjax::begin(); ?>
    <?php
    $this->registerJS(<<<JS

$('.rowTable').click(function(e) {
    window.location = '/admin-task-list/edit' + '?' + 'id' + '=' + $(this).data('id');
});

$('.buttonDelete').click(function (e) {
    e.preventDefault();
    e.stopPropagation();
    if (confirm('Подтвердите удаление')) {
        var button = $(this);
        var id = $(this).data('id');
        ajaxJson({
            url: '/admin-task-list/delete' + '?' + 'id' + '=' + id,
            success: function (ret) {
                $('#modalInfo').on('hidden.bs.modal', function() {
                    button.parent().parent().remove();
                }).modal();
            }
        });
    }
});

JS
    );
    ?>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query'      => \common\models\task\Task::find()
                ->where(['school_id' => $school->id])
            ->orderBy(['created_at' => SORT_DESC])
            ,
            'pagination' => [
                'pageSize' => 100,
            ],
        ]),
        'tableOptions' => [
            'class' => 'table table-striped table-hover',
        ],
        'rowOptions'   => function ($item) {
            $data = [
                'data'  => ['id' => $item['id']],
                'role'  => 'button',
                'class' => 'rowTable',
            ];
            return $data;
        },
        'columns'      => [
            'id',
            'name',
            [
                'header'  => 'Стоимость',
                'headerOptions' => [
                    'style' => Html::cssStyleFromArray([
                        'text-align' => 'right',
                    ])
                ],
                'contentOptions' => [
                    'style' => Html::cssStyleFromArray([
                        'text-align' => 'right',
                    ])
                ],
                'content' => function (\common\models\task\Task $item) {
                    if (empty($item->price)) {
                        return '';
                    }
                    return
                        $item->getPriceFormatted() . ' ' .
                        Html::tag('span', $item->getCurrency()->code, [
                            'class' => 'label label-info',
                        ]);
                },
            ],
            [
                'header'  => 'Удалить',
                'content' => function ($item) {
                    return Html::button('Удалить', [
                        'class' => 'btn btn-danger btn-xs buttonDelete',
                        'data'  => [
                            'id' => $item['id'],
                        ],
                    ]);
                },
            ],
        ],
    ]) ?>
    <?php \yii\widgets\Pjax::end(); ?>
    </div>

</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Информация</h4>
            </div>
            <div class="modal-body">
                Успешно!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>